Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
jjj
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    jjj
NameError: name 'jjj' is not defined

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 16, in <module>
    item_list.append()
NameError: name 'item_list' is not defined

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 17, in <module>
    item_list.append()
AttributeError: 'dict' object has no attribute 'append'

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 17, in <module>
    item_list.insert()
AttributeError: 'dict' object has no attribute 'insert'

==== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/gatau.py ===
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/gatau.py", line 9, in <module>
    kota()
TypeError: 'dict' object is not callable

==== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/gatau.py ===
10 -> Solo
15 -> Sukoharjo
20 -> Wonogiri
25 -> Sragen
30 -> Karanganyar
35 -> Boyolali

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 1, in <module>
    kota = {
TypeError: unhashable type: 'list'

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 1, in <module>
    kota = {
TypeError: unhashable type: 'list'

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 1, in <module>
    list = {
TypeError: unhashable type: 'list'

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
(['Solo', '10'], ['Sukoharjo', '15'], ['Wonogiri', '20'], ['Sragen', '25'], ['Karanganyar', '30'], ['Boyolali', '35'])
>>> 
=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
>>> 
=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 17, in <module>
    item_list.insert()
AttributeError: 'tuple' object has no attribute 'insert'
>>> 
= RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/table hash dan dungsi.py
['Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello']
>>> 
=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 10, in <module>
    item_list.insert()
TypeError: insert expected 2 arguments, got 0
>>> 
=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 10, in <module>
    item_list.insert()
TypeError: insert expected 2 arguments, got 0
>>> 
=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 10, in <module>
    kota.insert()
NameError: name 'kota' is not defined. Did you mean: 'Kota'?
>>> 
=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 10, in <module>
    Kota.insert()
TypeError: insert expected 2 arguments, got 0

Warning (from warnings module):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 3
    [15,"Sukoharjo"]
SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
>>> 
=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 3, in <module>
    [15,"Sukoharjo"]
TypeError: list indices must be integers or slices, not tuple

Warning (from warnings module):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 3
    [15,"Sukoharjo"]
SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
>>> 
=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 3, in <module>
    [15,"Sukoharjo"]
TypeError: list indices must be integers or slices, not tuple

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
10 -> Solo
15 -> Sukoharjo
20 -> Wonogiri
25 -> Sragen
30 -> Karanganyar
35 -> Boyolali
[[10, 'Solo'], [15, 'Sukoharjo'], [20, 'Wonogiri'], [25, 'Sragen'], [30, 'Karanganyar'], [35, 'Boyolali'], (40, 'Salatiga')]

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
10 -> Solo
15 -> Sukoharjo
20 -> Wonogiri
25 -> Sragen
30 -> Karanganyar
35 -> Boyolali
[[10, 'Solo'], [15, 'Sukoharjo'], [20, 'Wonogiri'], [25, 'Sragen'], [30, 'Karanganyar'], [35, 'Boyolali'], (40, 'Salatiga')]
masukkan kota yang dicari :
=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
10 -> Solo
15 -> Sukoharjo
20 -> Wonogiri
25 -> Sragen
30 -> Karanganyar
35 -> Boyolali
[[10, 'Solo'], [15, 'Sukoharjo'], [20, 'Wonogiri'], [25, 'Sragen'], [30, 'Karanganyar'], [35, 'Boyolali'], (40, 'Salatiga')]
masukkan kota yang dicari : 10
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 25, in <module>
    search(kota,key,value)
TypeError: search() takes 2 positional arguments but 3 were given

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
10 -> Solo
15 -> Sukoharjo
20 -> Wonogiri
25 -> Sragen
30 -> Karanganyar
35 -> Boyolali
[[10, 'Solo'], [15, 'Sukoharjo'], [20, 'Wonogiri'], [25, 'Sragen'], [30, 'Karanganyar'], [35, 'Boyolali'], (40, 'Salatiga')]
masukkan kota yang dicari :10, surakarta
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 25, in <module>
    search(key,value)
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 14, in search
    for item in item_list:
TypeError: 'int' object is not iterable

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
10 -> Solo
15 -> Sukoharjo
20 -> Wonogiri
25 -> Sragen
30 -> Karanganyar
35 -> Boyolali
[[10, 'Solo'], [15, 'Sukoharjo'], [20, 'Wonogiri'], [25, 'Sragen'], [30, 'Karanganyar'], [35, 'Boyolali'], (40, 'Salatiga')]
masukkan kota yang dicari :10,"solo"
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 25, in <module>
    search(key,value)
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 14, in search
    for item in item_list:
TypeError: 'int' object is not iterable

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
10 -> Solo
15 -> Sukoharjo
20 -> Wonogiri
25 -> Sragen
30 -> Karanganyar
35 -> Boyolali
[[10, 'Solo'], [15, 'Sukoharjo'], [20, 'Wonogiri'], [25, 'Sragen'], [30, 'Karanganyar'], [35, 'Boyolali'], (40, 'Salatiga')]
Solo

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
10 -> Solo
15 -> Sukoharjo
20 -> Wonogiri
25 -> Sragen
30 -> Karanganyar
35 -> Boyolali
[[10, 'Solo'], [15, 'Sukoharjo'], [20, 'Wonogiri'], [25, 'Sragen'], [30, 'Karanganyar'], [35, 'Boyolali'], (40, 'Salatiga')]
masukkan key kota :10
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 25, in <module>
    print(search(kota,key,value))
TypeError: search() takes 2 positional arguments but 3 were given

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
10 -> Solo
15 -> Sukoharjo
20 -> Wonogiri
25 -> Sragen
30 -> Karanganyar
35 -> Boyolali
[[10, 'Solo'], [15, 'Sukoharjo'], [20, 'Wonogiri'], [25, 'Sragen'], [30, 'Karanganyar'], [35, 'Boyolali'], (40, 'Salatiga')]
masukkan key kota : 10
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 25, in <module>
    print(search(key,value))
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py", line 14, in search
    for item in item_list:
TypeError: 'int' object is not iterable

=== RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/hashing.py ==
10 -> Solo
15 -> Sukoharjo
20 -> Wonogiri
25 -> Sragen
30 -> Karanganyar
35 -> Boyolali
[[10, 'Solo'], [15, 'Sukoharjo'], [20, 'Wonogiri'], [25, 'Sragen'], [30, 'Karanganyar'], [35, 'Boyolali'], (40, 'Salatiga')]
Sukoharjo

= RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/table hash dan dungsi.py
['Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello']

= RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/table hash dan dungsi.py
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/table hash dan dungsi.py", line 2, in <module>
    print (hash_table)
NameError: name 'hash_table' is not defined

= RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/table hash dan dungsi.py
[]
Traceback (most recent call last):
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/table hash dan dungsi.py", line 11, in <module>
    insert(hash_table,10,"Solo")
  File "C:/Users/asus/AppData/Local/Programs/Python/Python311/table hash dan dungsi.py", line 8, in insert
    hash_key = hash_func(key)
TypeError: hash_func() takes 0 positional arguments but 1 was given

= RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/table hash dan dungsi.py
[]

= RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/table hash dan dungsi.py
['Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello']

= RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/table hash dan dungsi.py
['Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello']
0

= RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/table hash dan dungsi.py
['Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello']
0
0
5

= RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/operasi insert data pada table.py
['Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello']

= RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/operasi insert data pada table.py
['Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello']
['Wonogiri', 'Hello', 'Hello', 'Hello', 'Hello', 'Sragen', 'Hello', 'Hello', 'Hello', 'Hello']

= RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/operasi insert data pada table.py
['Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello']
['Wonogiri', 'Hello', 'Solo', 'Hello', 'Hello', 'Sragen', 'Hello', 'Hello', 'Hello', 'Hello']

= RESTART: C:/Users/asus/AppData/Local/Programs/Python/Python311/operasi insert data pada table.py
['Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello', 'Hello']
['Wonogiri', 'Hello', 'Hello', 'Hello', 'Hello', 'Sragen', 'Hello', 'Hello', 'Hello', 'Hello']
